name = "supermarks-d1-bridge2"
main = "cloudflare/index.js"
compatibility_date = "2026-03-25"
workers_dev = true

[vars]
SUPERMARKS_ENV = "production"

[[d1_databases]]
binding = "SUPERMARKS_DB"
database_name = "supermarksdb"
database_id = "381cadf9-ec1e-4eb1-ad27-38c8986bd114"
preview_database_id = "381cadf9-ec1e-4eb1-ad27-38c8986bd114"
migrations_dir = "d1/migrations"
